pipeline {
  agent any

  environment {
    // Optional: configure NodeJS version label if using NodeJS plugin
    PATH = "/usr/bin:$PATH"
    EC2_IP = "3.253.112.162"
  }

  stages {
    stage('Install Dependencies') {
      steps {
        dir('angular-app/test-app') {
          sh 'npm install'
        }
      }
    }

    stage('Build Angular App') {
      steps {
        dir('angular-app/test-app') {
          sh 'npm run build'
        }
      }
    }
    
    stage('Fix SSH Host Key Trust') {
      steps {
        sh '''
          mkdir -p /var/lib/jenkins/.ssh
          ssh-keyscan -H $EC2_IP >> /var/lib/jenkins/.ssh/known_hosts

        '''
      }
    }
    
    stage('Deploy with Ansible') {
      steps {
        sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook.yml'
      }
    }
  }

  post {
    success {
      echo 'Deployment Successful!'
    }
    failure {
      echo 'Deployment Failed!'
    }
  }
}
