pipeline {
  agent any

  environment {
    // Optional: configure NodeJS version label if using NodeJS plugin
    PATH = "/usr/bin:$PATH"
  }

  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/Humaidu/tf-ansible-jenkins-angular-proj.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('angular-app/test-app') {
          sh 'npm install'
        }
      }
    }

    stage('Build Angular App') {
      steps {
        dir('angular-app/test-app') {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy with Ansible') {
      steps {
        sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook.yml'
      }
    }
  }

  post {
    success {
      echo 'Deployment Successful!'
    }
    failure {
      echo 'Deployment Failed!'
    }
  }
}
